package com.example.demomybatics.model;

public class student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.id
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.name
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.age
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Student.gender
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    private String gender;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.id
     *
     * @return the value of Student.id
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.id
     *
     * @param id the value for Student.id
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.name
     *
     * @return the value of Student.name
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.name
     *
     * @param name the value for Student.name
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.age
     *
     * @return the value of Student.age
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.age
     *
     * @param age the value for Student.age
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Student.gender
     *
     * @return the value of Student.gender
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Student.gender
     *
     * @param gender the value for Student.gender
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    public void setGender(String gender) {
        this.gender = gender;
    }
}