server:
  port: 8080

spring:
  security:
    user:
      name: username
      password: password
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=my-batis
    username: sa
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update

mybatis:
  mapper-locations: classpath:/com/example/demomybatics/mapper/*.xml
  type-aliases-package: com.example.demomybatics.model
