package com.example.demomybatics.mapper;

import com.example.demomybatics.model.student;
import com.example.demomybatics.model.studentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface studentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    long countByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    int deleteByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    int insert(student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    int insertSelective(student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    List<student> selectByExample(studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    student selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    int updateByExampleSelective(@Param("row") student row, @Param("example") studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    int updateByExample(@Param("row") student row, @Param("example") studentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    int updateByPrimaryKeySelective(student row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table Student
     *
     * @mbg.generated Mon Oct 28 20:41:02 GMT+07:00 2024
     */
    int updateByPrimaryKey(student row);
}