package com.example.demomybatics.mapper;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.springframework.security.access.prepost.PostAuthorize;

import com.example.demomybatics.model.student;
import com.example.demomybatics.model.studentExample;

@Mapper
public interface studentMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	long countByExample(studentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	int deleteByExample(studentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */

	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	int insert(student row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	int insertSelective(student row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	List<student> selectByExample(studentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	student selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	int updateByExampleSelective(@Param("row") student row, @Param("example") studentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	int updateByExample(@Param("row") student row, @Param("example") studentExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	int updateByPrimaryKeySelective(student row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to
	 * the database table Student
	 *
	 * @mbg.generated Sun Oct 27 14:50:09 GMT+07:00 2024
	 */
	int updateByPrimaryKey(student row);

	@PostAuthorize("returnObject.name == authentication.name")
	List<student> getAllStudent();

	List<student> getAllStudentByName(String name);

	List<Map<String, Object>> getAllStudentByNameIsMap(String name);

	List<student> getAllStudentByNameAndAge(Map<String, Object> valuePrame);

}